services:
  db:
    image: local/mariadb-nano
    container_name: cnt-db
    restart: unless-stopped
    ports:
      - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword

  
  phpmyadmin:
    image: local/pma
    container_name: cnt-pma
    restart: unless-stopped
    ports:
      - "8080:80"
    # environment:
    #   PMA_HOST: cnt-db
    #   PMA_PORT: 3306
    #   PMA_USER: root
    #   PMA_PASSWORD: rootpassword
    # depends_on:
    #   - db

networks:
  default:
    name: localnet