services:
  wordpress:
    image: local/wordpress-deepseek
    container_name: cnt-wordpress
    restart: unless-stopped
    ports:
      - "80:80"

networks:
  default:
    external: true
    name: localnet